# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_drop_billable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority', 'client', 'name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='cgac_agency_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='omb_bureau_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='treasury_agency_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mb_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tock_id',
        ),
        migrations.AddField(
            model_name='project',
            name='agency_effort',
            field=models.IntegerField(default=0, help_text='Estimate of Agency staff necessary for the project.', verbose_name='Agency Staff Level of Effort'),
        ),
        migrations.AddField(
            model_name='project',
            name='blockers',
            field=models.TextField(blank=True, help_text='What stands in the way of this project? Markdown is allowed.'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_effort',
            field=models.IntegerField(default=0, help_text='Estimate of contractor staff necessary for the project.', verbose_name='Contractor Staff Level of Effort'),
        ),
        migrations.AddField(
            model_name='project',
            name='go_live_date',
            field=models.DateField(blank=True, help_text='The estimated or actual project go-live date.', null=True, verbose_name='Project Go-Live Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Designated Strategic Imperative'), (1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=3, help_text='Official designated priority of the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='rifans_number',
            field=models.CharField(blank=True, help_text='The unique identifier for the project inthe RIFANS financial system.', max_length=100, verbose_name='MB Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='The estimated or actual project start date.', null=True, verbose_name='Project Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_effort',
            field=models.IntegerField(default=0, help_text='Estimate of technical staff necessary for the project.', verbose_name='Tech Staff Level of Effort'),
        ),
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.CharField(blank=True, help_text='Department is the highest organizational level.', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='omb_agency_code',
            field=models.CharField(blank=True, help_text='OMB Agency Code is the code id for the agency described here.', max_length=255, verbose_name='OMB Agency Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_unit',
            field=models.ForeignKey(blank=True, default=None, help_text='The Business Unit that owns the project.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='The GitHub URL of the project, e.g. https://github.com/401ode/analytics-reporter', verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Whether or not the project is chargeable to a non-ODE/ETSS client.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='The full name of the project (e.g., "UHIP")', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.CharField(blank=True, help_text='Name of ETSS/ODE employee who is responsible for this project.', max_length=255, verbose_name='Project Lead'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='The slug of the project (e.g., "uhip")', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(help_text='Which categories does this project fall into?', to='projects.Category'),
        ),
    ]
