# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.PositiveIntegerField(choices=[(0, 'Project'), (1, 'Funding Source')]),
        ),
    ]
