# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20161004_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.PositiveIntegerField(choices=[(0, 'Project'), (1, 'Funding Source')], default=0),
            preserve_default=False,
        ),
    ]
