# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20161004_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.PositiveIntegerField(choices=[(0, 'Project'), (1, 'Funding Source')], default=0),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
