# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20161005_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='dollar_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount budgeted for this funding source.', max_digits=11),
        ),
    ]
