# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20161005_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='go_live_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='completion_fy',
            field=models.ForeignKey(help_text='The estimated or actual project completion Fiscal Year.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_complete_in_this_fy', to='projects.FiscalYear', verbose_name='Project Completion'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_fy',
            field=models.ForeignKey(help_text='The estimated or actual project starting Fiscal Year.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_starting_in_this_fy', to='projects.FiscalYear', verbose_name='Project Start'),
        ),
    ]
