# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 15:05
from __future__ import unicode_literals

from django.db import migrations
from projects.models import Category

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20161005_1025'),
    ]

    operations = [
        # Get all category objects.
        categories = Category.objects.all()
        for cat in categories:
            if cat.category_type == "Project":
                cat.category_type = 0
        categories.save()
    ]
