# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20161028_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(help_text='Primary Contact for this project.', to='projects.Contact'),
        ),
    ]
