# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blocker_description', models.TextField(help_text="Add as many blockers as are necessary to describe whatis preventing this project from moving forward. Don't worryabout category accuracy - this is for general guidance, notreporting.", max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note_text', models.TextField(help_text='What should we know about this project?', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='blockers',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.PositiveIntegerField(choices=[(0, 'Project'), (1, 'Funding Source'), (2, 'Blocker'), (3, 'Note')], default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='note_category',
            field=models.ForeignKey(help_text='Category for this note.', on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='blocker',
            name='blocker_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
        ),
        migrations.AddField(
            model_name='blocker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
