language: python
python:
  - 3.5.2
services:
  - postgresql
env:
  - TRAVIS_NODE_VERSION="4.4"
install:
  - pip install -r requirements.txt
script:
  # - pylint --rcfile=.pylintrc
  - python manage.py test --nomigrations
